#pragma once

typedef enum {
    ZMK_USB_BRIDGE_BLE_COMMAND_NONE = 0,
    ZMK_USB_BRIDGE_BLE_COMMAND_START_PAIRING_SCAN,
    ZMK_USB_BRIDGE_BLE_COMMAND_START_KNOWN_DEVICE_SCAN,
    ZMK_USB_BRIDGE_BLE_COMMAND_ENTER_RECONNECT_FAST,
    ZMK_USB_BRIDGE_BLE_COMMAND_ENTER_RECONNECT_BACKOFF,
    ZMK_USB_BRIDGE_BLE_COMMAND_STOP_SCAN,
    ZMK_USB_BRIDGE_BLE_COMMAND_ERASE_BONDS,
} zmk_usb_bridge_ble_command_t;
