#pragma once

typedef enum {
    ZMK_USB_BRIDGE_STATUS_OK = 0,
    ZMK_USB_BRIDGE_STATUS_INVALID_ARGUMENT = -1,
    ZMK_USB_BRIDGE_STATUS_INVALID_STATE = -2,
    ZMK_USB_BRIDGE_STATUS_NOT_FOUND = -3,
    ZMK_USB_BRIDGE_STATUS_NO_MEMORY = -4,
    ZMK_USB_BRIDGE_STATUS_QUEUE_FULL = -5,
    ZMK_USB_BRIDGE_STATUS_SIZE_MISMATCH = -6,
} zmk_usb_bridge_status_t;
