#pragma once

#include "zmk_usb_bridge/bridge.h"
#include "zmk_usb_bridge/status.h"

zmk_usb_bridge_status_t zmk_usb_bridge_usb_bridge_init(void);
zmk_usb_bridge_status_t zmk_usb_bridge_usb_bridge_send_keyboard(const zmk_usb_bridge_keyboard_body_t *body);
zmk_usb_bridge_status_t zmk_usb_bridge_usb_bridge_send_consumer(const zmk_usb_bridge_consumer_body_t *body);
zmk_usb_bridge_status_t zmk_usb_bridge_usb_bridge_send_mouse(const zmk_usb_bridge_mouse_body_t *body);
zmk_usb_bridge_status_t zmk_usb_bridge_usb_bridge_release_all(void);
