# User-editable config fragment.
#
# Example:
# CONFIG_ZMK_USB_BRIDGE_PAIRING_NAME_ALLOWLIST_ENABLED=y
# CONFIG_ZMK_USB_BRIDGE_PAIRING_NAME_ALLOWLIST="LaLapadGen2"

CONFIG_ZMK_USB_BRIDGE_PAIRING_NAME_ALLOWLIST_ENABLED=y
CONFIG_ZMK_USB_BRIDGE_PAIRING_NAME_ALLOWLIST="LalapadGen2"
